name: CI
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Node deps
        run: npm ci || npm install

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Smoke test Python backend imports
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python - <<'PY'
import importlib, sys
print("PYTHONPATH OK, sys.path[0] =", sys.path[0])
for m in ("python.image_processing", "python.model"):
    importlib.import_module(m)
print("Python backend imports OK")
PY
